[build]
  publish = "public/"
  command = "npm run build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "public/assets/images", # Processed images
    "public/assets/fonts",  # Fonts (woff2, etc.)
    "public/assets/favicons", # Favicons
    "public/assets/svgs",   # Preloaded SVGs
    ".cache" # Remote Assets
  ]
